[save]
save_dir = "configs"
filename_format = "pulse_control_20260216_"

[connection]
visa_address = "TCPIP0::192.168.0.251::5025::SOCKET"

[common]
v_on = 0.13
v_off = 2.13
frequency = 5000000.0
period = 2e-7
trigger_delay = 3184
resolution_n = 2

[simple_pulse]
pulse_width = 1.6e-7
saved_records = [ [ 2.5e-9, 2728,], [ 5e-9, 2816,], [ 1e-8, 2912,], [ 2e-8, 3032,], [ 4e-8, 3112,], [ 8e-8, 3160,], [ 1.2000000000000002e-7, 3176,], [ 1.6e-7, 3184,],]

[width_sweep]
width_start = 2.5e-9
width_stop = 1.6e-7
width_step = 2.5e-9
wait_time = 2.5
settling_time = 2.0
trigger_delay_stop = 0
delay_mode = "table"
delay_table = [ [ 2.5e-9, 2728,], [ 5e-9, 2816,], [ 1e-8, 2912,], [ 2e-8, 3032,], [ 4e-8, 3112,], [ 8e-8, 3160,], [ 1.2000000000000002e-7, 3176,], [ 1.6e-7, 3184,],]

[delay_sweep]
pulse_width = 1e-8
wait_time = 0.04
delay_start = 0
delay_stop = 6400
delay_step = 16
settling_time = 2.0
